### ISSUE TITLE
Just installed, tons of errors though?

### ISSUE THREAD

**Issue by MostHated** [binaryitch/infected#1]
Hey there, 
    I was trying to find a good demo of seeing ECS in action so I can look it over and see how its done. I saw yours was recently updated, so I figured it was probably working ok, I imported it but I got a ton of errors as seen below. Am I possibly missing something or just it just have errors? I am using 2018.2.8f1 and I have Burst, Entities, and Addressables, its the versions you had in the package manifest.

Thanks,
-MH

[https://i.imgur.com/rBEIPP2.png](url)

**Comment by MostHated** [comment]
Awesome, I will give it a go now. Thanks, I appreciate it!

**Comment by MostHated** [comment]
I must be doing something wrong. This is what I am currently getting for errors now after having put in your framework. I tried 2018.2.8f1 first, but that didn't work, 2018.2.7f1 worked for some other projects, but it's not for yours (for me at least). What version are you using for this?

https://i.imgur.com/hrj76ZR.png

**Comment by binaryitch** [comment]
Strange one, I've had it working with all 2018.2 releases since 2018.2.3xx, although I've not tried. 2.8. Did you add or remove any usings to/from any of the ECS scripts? Using both math APIs will lead to ambiguities such as those above.

Glad you got it working :)

**Comment by MostHated** [comment]
At first I attempted it when I was using 2018.2.8f1, but then I just deleted it all, extracted it fresh, and then when I used 6f1 it worked just fine as it was.
